### ISSUE TITLE
Additional Fire-able items for the Gravity Gun

### ISSUE THREAD

**Issue by Toxici11i** [TheGoldenGuardian/BTEPlus#2]
Heya, could you make the gravity gun be able to fire all non-weapon materials that are smaller than tables? i believe that it would make the gravity gun much more fun than just firing tables(propelling nuclear charges at people ayylmao)

**Comment by TheGoldenGuardian** [comment]
I could, the problem with this is I'd have to add a "Projectile" segment to each and every single item I want the Gravity Gun to be able to fire, you should probably understand why it's not yet craftable. I plan to add more containers to its firing list, things that can't be stored and normally wouldn't be projectiles anyways.

**Comment by TheGoldenGuardian** [comment]
Unfortunately, the Gravity Gun has been removed.
It would simply be too much of a hassle.
