### ISSUE TITLE
Breaching Kit and Gas Bottles

### ISSUE THREAD

**Issue by AS-1648** [TheGoldenGuardian/BTEPlus#3]
Basically, I'm envisioning a grenade belt and smaller gas tanks, called gas **bottles**, which also fit on the belt. I've been calling this the breaching kit, since oxygen bottles and grenades would be very useful for boarding actions, but this name's obviously not set in stone.

The object shouldn't be worn due to constraints with the inventory system at present.

Note that this was rejected by Chiko for the time being because one could carry a shitload of these; this was part of the reason for proposing smaller gas tanks to go with it. That and volume.

I have a sprite for the belt itself on hand, available on request.

**Comment by TheGoldenGuardian** [comment]
Slot count? Should it be able to hold **all** `smallitem`s? Crafting recipe?

**Comment by AS-1648** [comment]
I would say...
- Bottles should only fit in this item and in the magic pockets.
- Crafting recipe, not-insignificant quantities of polycarb (both for the belt itself and padding of the pockets) and somewhat smaller amounts of steel (structural elements and buckles).
- Slot count 4-6, though obviously anything greater than 1 makes it useful.

**Comment by TheGoldenGuardian** [comment]
How do you mean `bottles should only fit in this`?
I was thinking the kit could only be made to hold all Grenade types as well as the Oxy Bottles

On the subject of crafting, Polycarbonate Bar and Steel Sliver?
What about for the Bottles? Aluminum Sliver? A regular Oxy Tank requires a Bar so it makes sense.

For the slot count:
I'll make it 6.
